from utils.db import db
from datetime import datetime

class EstSum (db.Model):
    __tablename__ = 'est_sum'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(255))
    
class Estado (db.Model):
    __tablename__ = 'estado'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(255))
    
class Mercado (db.Model):
    __tablename__ = 'mercado'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(255))
    
class Territorio (db.Model):
    __tablename__ = 'territorio'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(255))

class TipoTension (db.Model):
    __tablename__ = 'tipo_tension'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(255))
    
class NomMunic (db.Model):
    __tablename__ = 'nom_munic'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(255))
class NomDepto (db.Model):
    __tablename__ = 'nom_depto'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(255))
class NomProv (db.Model):
    __tablename__ = 'nom_prov'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(255))
class TipoUbicacion (db.Model):
    __tablename__ = 'tipo_ubicacion'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(255))

class Consumo(db.Model):
    __tablename__ = 'consumo'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    periodo_analisis = db.Column(db.String)
    periodo_ejecucion = db.Column(db.String)
    nis_rad = db.Column(db.String)
    nic = db.Column(db.String)
    codigo_sic = db.Column(db.String)
    nif = db.Column(db.String)
    nombre = db.Column(db.String)
    id_est_sum = db.Column(db.Integer, db.ForeignKey('est_sum.id'))
    id_estado = db.Column(db.Integer, db.ForeignKey('estado.id'))
    id_mercado =  db.Column(db.Integer, db.ForeignKey('mercado.id'))
    id_territorio = db.Column(db.Integer, db.ForeignKey('territorio.id'))
    zona = db.Column(db.String)
    desc_cnae = db.Column(db.String)
    f_alta = db.Column(db.DateTime)
    f_baja = db.Column(db.DateTime)
    co_asignacion = db.Column(db.String)
    tipo_suministro = db.Column(db.String)
    tipo_asoc = db.Column(db.String)
    id_tipo_tension = db.Column(db.Integer, db.ForeignKey('territorio.id'))
    tarifa = db.Column(db.String)
    descripcion_tarifa = db.Column(db.String)
    num_apa = db.Column(db.String)
    f_inst = db.Column(db.DateTime)
    f_lvto = db.Column(db.DateTime)
    tipo_fase = db.Column(db.String)
    codigo_marca = db.Column(db.String)
    cod_local = db.Column(db.String)
    nom_local = db.Column(db.String)
    id_nom_munic = db.Column(db.Integer, db.ForeignKey('nom_munic.id'))
    id_nom_depto = db.Column(db.Integer, db.ForeignKey('nom_depto.id'))
    id_nom_prov = db.Column(db.Integer, db.ForeignKey('nom_prov.id'))
    tipo_ubicacion = db.Column(db.String)
    direccion = db.Column(db.String)
    nombre_salmt = db.Column(db.String)
    multifamiliar = db.Column(db.String)
    ruta = db.Column(db.Integer)
    num_itin = db.Column(db.Integer)
    csmo_activa_f_pico = db.Column(db.Float)
    csmo_activa_pico = db.Column(db.Float)
    csmo_reactiva = db.Column(db.Float)
    lectura_activa = db.Column(db.Float)
    lectura_activa_f_pico = db.Column(db.Float)
    lectura_activa_pico = db.Column(db.Float)
    lectura_reactiva = db.Column(db.Float)
    nivel_tension = db.Column(db.String)
    meses_en_altasinfact_pendconexion = db.Column(db.Integer)
    rango_meses_en_altasinfact_pendconexion = db.Column(db.String)
    segmento = db.Column(db.String)
    anomfact = db.Column(db.Integer)
    anom_202212 = db.Column(db.Float)
    anom_202301 = db.Column(db.Float)
    anom_202302 = db.Column(db.Float)
    anom_202303 = db.Column(db.Float)
    anom_202304 = db.Column(db.Float)
    anom_202305 = db.Column(db.Float)
    anom_202306 = db.Column(db.Float)
    anom_202307 = db.Column(db.Float)
    anom_202308 = db.Column(db.Float)
    anom_202309 = db.Column(db.Float)
    anom_202310 = db.Column(db.Float)
    anom_202311 = db.Column(db.Float)
    anom_202312 = db.Column(db.Float)
    tipo_anl_mes_anterior = db.Column(db.String)
    cantidad_consc_candidatos_anl_a_partir_del_mes_anterior = db.Column(db.Integer)
    cantidad_consc_anl_a_partir_mes_anterior = db.Column(db.Integer)
    ultima_anl = db.Column(db.Integer)
    periodo_ultima_anl = db.Column(db.Integer)
    est_202212 = db.Column(db.String)
    est_202301 = db.Column(db.String)
    est_202302 = db.Column(db.String)
    est_202303 = db.Column(db.String)
    est_202304 = db.Column(db.String)
    est_202305 = db.Column(db.String)
    est_202306 = db.Column(db.String)
    est_202307 = db.Column(db.String)
    est_202308 = db.Column(db.String)
    est_202309 = db.Column(db.String)
    est_202310 = db.Column(db.String)
    est_202311 = db.Column(db.String)
    est_202312 = db.Column(db.String)
    csmo_201801 = db.Column(db.Float)
    csmo_201802 = db.Column(db.Float)
    csmo_201803 = db.Column(db.Float)
    csmo_201804 = db.Column(db.Float)
    csmo_201805 = db.Column(db.Float)
    csmo_201806 = db.Column(db.Float)
    csmo_201807 = db.Column(db.Float)
    csmo_201808 = db.Column(db.Float)
    csmo_201809 = db.Column(db.Float)
    csmo_201810 = db.Column(db.Float)
    csmo_201811 = db.Column(db.Float)
    csmo_201812 = db.Column(db.Float)
    csmo_201901 = db.Column(db.Float)
    csmo_201902 = db.Column(db.Float)
    csmo_201903 = db.Column(db.Float)
    csmo_201904 = db.Column(db.Float)
    csmo_201905 = db.Column(db.Float)
    csmo_201906 = db.Column(db.Float)
    csmo_201907 = db.Column(db.Float)
    csmo_201908 = db.Column(db.Float)
    csmo_201909 = db.Column(db.Float)
    csmo_201910 = db.Column(db.Float)
    csmo_201911 = db.Column(db.Float)
    csmo_201912 = db.Column(db.Float)
    csmo_202001 = db.Column(db.Float)
    csmo_202002 = db.Column(db.Float)
    csmo_202003 = db.Column(db.Float)
    csmo_202004 = db.Column(db.Float)
    csmo_202005 = db.Column(db.Float)
    csmo_202006 = db.Column(db.Float)
    csmo_202007 = db.Column(db.Float)
    csmo_202008 = db.Column(db.Float)
    csmo_202009 = db.Column(db.Float)
    csmo_202010 = db.Column(db.Float)
    csmo_202011 = db.Column(db.Float)
    csmo_202012 = db.Column(db.Float)
    csmo_202101 = db.Column(db.Float)
    csmo_202102 = db.Column(db.Float)
    csmo_202103 = db.Column(db.Float)
    csmo_202104 = db.Column(db.Float)
    csmo_202105 = db.Column(db.Float)
    csmo_202106 = db.Column(db.Float)
    csmo_202107 = db.Column(db.Float)
    csmo_202108 = db.Column(db.Float)
    csmo_202109 = db.Column(db.Float)
    csmo_202110 = db.Column(db.Float)
    csmo_202111 = db.Column(db.Float)
    csmo_202112 = db.Column(db.Float)
    csmo_202201 = db.Column(db.Float)
    csmo_202202 = db.Column(db.Float)
    csmo_202203 = db.Column(db.Float)
    csmo_202204 = db.Column(db.Float)
    csmo_202205 = db.Column(db.Float)
    csmo_202206 = db.Column(db.Float)
    csmo_202207 = db.Column(db.Float)
    csmo_202208 = db.Column(db.Float)
    csmo_202209 = db.Column(db.Float)
    csmo_202210 = db.Column(db.Float)
    csmo_202211 = db.Column(db.Float)
    csmo_202212 = db.Column(db.Float)
    csmo_202301 = db.Column(db.Float)
    csmo_202302 = db.Column(db.Float)
    csmo_202303 = db.Column(db.Float)
    csmo_202304 = db.Column(db.Float)
    csmo_202305 = db.Column(db.Float)
    csmo_202306 = db.Column(db.Float)
    csmo_202307 = db.Column(db.Float)
    csmo_202308 = db.Column(db.Float)
    csmo_202309 = db.Column(db.Float)
    csmo_202310 = db.Column(db.Float)
    csmo_202311 = db.Column(db.Float)
    csmo_202312 = db.Column(db.Float)
    dias_real = db.Column(db.Integer)
    dias_plan = db.Column(db.Integer)
    cant_os = db.Column(db.Integer)
    cant_irr = db.Column(db.Integer)
    ult_f_rev = db.Column(db.DateTime)
    ult_rev_res = db.Column(db.DateTime)
    nuevo_sum = db.Column(db.String)
    antg_medidor = db.Column(db.String)
    asoc_pd_hj = db.Column(db.String)
    fact_util = db.Column(db.Float)
    csmo_proyectado = db.Column(db.Float)
    desv_abs = db.Column(db.Float)
    mean_5perc = db.Column(db.Float)
    perc_dev = db.Column(db.Float)
    csmo_estc = db.Column(db.String)
    csmo_proy_agenda = db.Column(db.Float)
    csmo_norm_202201 = db.Column(db.Float)
    csmo_norm_202202 = db.Column(db.Float)
    csmo_norm_202203 = db.Column(db.Float)
    csmo_norm_202204 = db.Column(db.Float)
    csmo_norm_202205 = db.Column(db.Float)
    csmo_norm_202206 = db.Column(db.Float)
    csmo_norm_202207 = db.Column(db.Float)
    csmo_norm_202208 = db.Column(db.Float)
    csmo_norm_202209 = db.Column(db.Float)
    csmo_norm_202210 = db.Column(db.Float)
    csmo_norm_202211 = db.Column(db.Float)
    csmo_norm_202212 = db.Column(db.Float)